# Generated by Django 2.2.1 on 2019-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='upload_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
