# Generated by Django 2.2.3 on 2019-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_number_of_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_training',
            field=models.CharField(max_length=50),
        ),
    ]
