# Generated by Django 2.2.1 on 2019-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_upload_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='upload_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
